"""Add question versioning

Revision ID: 174cd96871ec
Revises: be905a4265b8
Create Date: 2025-12-28 11:31:59.955844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '174cd96871ec'
down_revision: Union[str, None] = 'be905a4265b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_tag',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.drop_table('question_tags')
    op.add_column('exam_question', sa.Column('question_version', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('base_question_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'question', 'question', ['base_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'base_question_id')
    op.drop_column('question', 'version')
    op.drop_column('exam_question', 'question_version')
    op.create_table('question_tags',
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('question_tags_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('question_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('question_id', 'tag_id', name=op.f('question_tags_pkey'))
    )
    op.drop_table('question_tag')
    # ### end Alembic commands ###
