"""Add cascade delete to exam relations

Revision ID: 1f59c31ff1c1
Revises: c16cadd26feb
Create Date: 2025-12-18 10:59:20.952771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1f59c31ff1c1'
down_revision: Union[str, None] = 'c16cadd26feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exam_answer_exam_question_id_fkey'), 'exam_answer', type_='foreignkey')
    op.create_foreign_key(None, 'exam_answer', 'exam_question', ['exam_question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('exam_question_exam_id_fkey'), 'exam_question', type_='foreignkey')
    op.create_foreign_key(None, 'exam_question', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_question', type_='foreignkey')
    op.create_foreign_key(op.f('exam_question_exam_id_fkey'), 'exam_question', 'exam', ['exam_id'], ['id'])
    op.drop_constraint(None, 'exam_answer', type_='foreignkey')
    op.create_foreign_key(op.f('exam_answer_exam_question_id_fkey'), 'exam_answer', 'exam_question', ['exam_question_id'], ['id'])
    # ### end Alembic commands ###
