"""Add exam attributes to table

Revision ID: 1f8e8f4aae40
Revises: 9a491c45944a
Create Date: 2025-12-27 14:51:51.969040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1f8e8f4aae40'
down_revision: Union[str, None] = '9a491c45944a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_tags',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('exam_id', 'tag_id')
    )
    op.add_column('exam', sa.Column('question_count', sa.Integer(), nullable=False))
    op.add_column('exam', sa.Column('filters', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'filters')
    op.drop_column('exam', 'question_count')
    op.drop_table('exam_tags')
    # ### end Alembic commands ###
