"""Add created_at to exams

Revision ID: 5274e0efe28c
Revises: 4c2d1f8a9b7e
Create Date: 2026-04-26 11:57:28.380746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5274e0efe28c'
down_revision: Union[str, None] = '4c2d1f8a9b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'created_at')
    # ### end Alembic commands ###
