"""Update question delete constraints

Revision ID: 6bea18b36faf
Revises: 73ce65ed34a1
Create Date: 2025-12-17 15:44:36.000431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6bea18b36faf'
down_revision: Union[str, None] = '73ce65ed34a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answer_choice_question_id_fkey'), 'answer_choice', type_='foreignkey')
    op.create_foreign_key(None, 'answer_choice', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('question_tags_question_id_fkey'), 'question_tags', type_='foreignkey')
    op.create_foreign_key(None, 'question_tags', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_tags', type_='foreignkey')
    op.create_foreign_key(op.f('question_tags_question_id_fkey'), 'question_tags', 'question', ['question_id'], ['id'])
    op.drop_constraint(None, 'answer_choice', type_='foreignkey')
    op.create_foreign_key(op.f('answer_choice_question_id_fkey'), 'answer_choice', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
