"""Add deleted_at to exam

Revision ID: 6e69036620d7
Revises: 1f59c31ff1c1
Create Date: 2025-12-18 11:05:32.308667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6e69036620d7'
down_revision: Union[str, None] = '1f59c31ff1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'deleted_at')
    # ### end Alembic commands ###
