"""Update exam table

Revision ID: 72e2b2aa7149
Revises: 6bea18b36faf
Create Date: 2025-12-18 09:10:27.978214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '72e2b2aa7149'
down_revision: Union[str, None] = '6bea18b36faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
