"""Add soft delete to questions

Revision ID: 73ce65ed34a1
Revises: e6f214aea369
Create Date: 2025-12-17 15:25:36.393305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '73ce65ed34a1'
down_revision: Union[str, None] = 'e6f214aea369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'deleted_at')
    # ### end Alembic commands ###
