"""Add updated at column to exam table

Revision ID: 848c35a3c283
Revises: 72e2b2aa7149
Create Date: 2025-12-18 09:43:12.722719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '848c35a3c283'
down_revision: Union[str, None] = '72e2b2aa7149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('exam', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('exam', 'updated_at')
    # ### end Alembic commands ###
