"""Update media columns in question table

Revision ID: 9a491c45944a
Revises: 6e69036620d7
Create Date: 2025-12-18 13:22:03.502631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a491c45944a'
down_revision: Union[str, None] = '6e69036620d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_answer', 'completed_at')
    op.add_column('question', sa.Column('media_storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('question', sa.Column('media_content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('question', 'media_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('question', 'media_content_type')
    op.drop_column('question', 'media_storage_path')
    op.add_column('exam_answer', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
