"""Rename exam tag table

Revision ID: be905a4265b8
Revises: 1f8e8f4aae40
Create Date: 2025-12-27 15:04:17.719777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'be905a4265b8'
down_revision: Union[str, None] = '1f8e8f4aae40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_tag',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('exam_id', 'tag_id')
    )
    op.drop_table('exam_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_tags',
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('exam_tags_exam_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('exam_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('exam_id', 'tag_id', name=op.f('exam_tags_pkey'))
    )
    op.drop_table('exam_tag')
    # ### end Alembic commands ###
