"""Add time tracking to exam answer

Revision ID: c16cadd26feb
Revises: 848c35a3c283
Create Date: 2025-12-18 09:46:57.549193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c16cadd26feb'
down_revision: Union[str, None] = '848c35a3c283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_answer', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('exam_answer', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_answer', 'completed_at')
    op.drop_column('exam_answer', 'started_at')
    # ### end Alembic commands ###
