"""Add timestamps to question table

Revision ID: e61962afe482
Revises: 174cd96871ec
Create Date: 2025-12-28 12:50:28.474165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e61962afe482'
down_revision: Union[str, None] = '174cd96871ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('question', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'updated_at')
    op.drop_column('question', 'created_at')
    # ### end Alembic commands ###
